using System.Globalization;
using System.Reflection;
using System.Text;

namespace StreamDeckPluginSharp.TypeGen;

public static class Program
{
    public static int Main(string[] args)
    {
        if (args.Length < 2)
        {
            Console.Error.WriteLine("Usage: sdps-typegen <assembly.dll> <output.ts> [attributeName]");
            return 1;
        }

        var assemblyPath = Path.GetFullPath(args[0]);
        var outputPath = Path.GetFullPath(args[1]);
        var attributeName = args.Length > 2 ? args[2] : "TypeScriptContractAttribute";

        var typescript = Generate(assemblyPath, attributeName);
        Directory.CreateDirectory(Path.GetDirectoryName(outputPath)!);
        File.WriteAllText(outputPath, typescript);
        Console.WriteLine($"Wrote TypeScript contracts to {outputPath}");
        return 0;
    }

    public static string Generate(string assemblyPath, string attributeName = "TypeScriptContractAttribute")
    {
        var assembly = Assembly.LoadFrom(assemblyPath);
        var types = assembly.GetTypes()
            .Where(type => type.GetCustomAttributes(inherit: false).Any(attribute => attribute.GetType().Name == attributeName))
            .OrderBy(type => type.Name)
            .ToArray();

        var builder = new StringBuilder();
        builder.AppendLine("// Generated by StreamDeckPluginSharp.TypeGen. Do not edit.");
        builder.AppendLine();

        foreach (var type in types)
        {
            if (type.IsEnum)
            {
                WriteEnum(builder, type);
            }
            else
            {
                WriteInterface(builder, type);
            }

            builder.AppendLine();
        }

        return builder.ToString();
    }

    private static void WriteEnum(StringBuilder builder, Type type)
    {
        var names = Enum.GetNames(type);
        var values = names.Select(name =>
        {
            var raw = Convert.ToInt64(Enum.Parse(type, name), CultureInfo.InvariantCulture);
            return $"  {Camel(name)} = {raw}";
        });
        builder.AppendLine($"export enum {type.Name} {{");
        builder.AppendLine(string.Join(",\n", values));
        builder.AppendLine("}");
    }

    private static void WriteInterface(StringBuilder builder, Type type)
    {
        builder.AppendLine($"export interface {type.Name} {{");
        foreach (var property in type.GetProperties(BindingFlags.Public | BindingFlags.Instance))
        {
            if (property.GetIndexParameters().Length > 0)
            {
                continue;
            }

            var optional = IsNullable(property) ? "?" : "";
            builder.AppendLine($"  {Camel(property.Name)}{optional}: {ToTypeScript(property.PropertyType)};");
        }

        builder.AppendLine("}");
    }

    private static bool IsNullable(PropertyInfo property)
    {
        if (!property.PropertyType.IsValueType)
        {
            return new NullabilityInfoContext().Create(property).WriteState is NullabilityState.Nullable;
        }

        return Nullable.GetUnderlyingType(property.PropertyType) is not null;
    }

    internal static string ToTypeScript(Type type)
    {
        type = Nullable.GetUnderlyingType(type) ?? type;
        if (type == typeof(string) || type == typeof(Guid) || type == typeof(DateTime) || type == typeof(DateTimeOffset))
        {
            return "string";
        }

        if (type == typeof(bool))
        {
            return "boolean";
        }

        if (type.IsEnum)
        {
            return type.Name;
        }

        if (type.IsPrimitive || type == typeof(decimal))
        {
            return "number";
        }

        if (type.IsArray)
        {
            return $"{ToTypeScript(type.GetElementType()!)}[]";
        }

        if (type.IsGenericType && typeof(IEnumerable<>).IsAssignableFrom(type.GetGenericTypeDefinition()) ||
            type.GetInterfaces().Any(i => i.IsGenericType && i.GetGenericTypeDefinition() == typeof(IEnumerable<>)))
        {
            var item = type.IsGenericType
                ? type.GetGenericArguments()[0]
                : type.GetInterfaces().First(i => i.IsGenericType && i.GetGenericTypeDefinition() == typeof(IEnumerable<>)).GetGenericArguments()[0];
            if (type.GetGenericArguments().Length == 2 && type.GetInterfaces().Any(i => i.IsGenericType && i.GetGenericTypeDefinition() == typeof(IDictionary<,>)))
            {
                return $"Record<string, {ToTypeScript(type.GetGenericArguments()[1])}>";
            }

            return $"{ToTypeScript(item)}[]";
        }

        return type.Name;
    }

    internal static string Camel(string name)
    {
        if (string.IsNullOrEmpty(name) || char.IsLower(name[0]))
        {
            return name;
        }

        return char.ToLowerInvariant(name[0]) + name[1..];
    }
}
